title: I'm Shahar Yakov!
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shaharyak.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Shahar Yakov # add your name
author-img: shahar-yakov.jpg # add your photo
about-author:  I'm highly motivated and passionate about building amazing products.
Eager to challenge the reality and make things better.
I'm doing so by constant feedback loops and reflections.
I give data respect, but believe that sometimes common sense beats it.
I've worked in both early-stage and mature startups.
I'm an IDF Mamram veteran holding a B.Sc in computer science.
social-twitter: Shahar_Yakov
# social-facebook: # add your Facebook handle
social-github: ShaharYak
social-linkedin: shahar-yakov-a8391b197
social-email: shahar321@gmail.com

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
